# fly.toml app configuration file generated for chirpy on 2025-02-13T20:32:35Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'chirpy'
primary_region = 'yyz'

[build]
  [build.args]
    GO_VERSION = '1.23.5'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[http_service]
  auto_stop_machines = false
  auto_start_machines = true
